#!/bin/bash

# Creates a `requirements.txt` file from top-level dependencies stored in `requirements-core.txt`
# This file should be executed whenever a change is made to `requirements-core.txt`

set -ef

# Remove and re-create venv dir
rm -rf venv-freeze
virtualenv -p python3 venv-freeze

# Install top-level requirements
venv-freeze/bin/pip install -r requirements-core.txt

# Write new `requirements.txt`, which includes any sub-dependencies
echo '# This file is autogenerated. Do not edit it manually.' > requirements.txt
echo '# BEGIN: `requirements-core.txt`' >> requirements.txt
cat requirements-core.txt >> requirements.txt
echo '# END: `requirements-core.txt`' >> requirements.txt
echo -e '\n\n' >> requirements.txt

venv-freeze/bin/pip freeze -r requirements-core.txt | sed -n '/The following requirements were added by pip freeze/,$p' >> requirements.txt

# Clean up
rm -rf venv-freeze
